/* eslint-disable @next/next/no-sync-scripts */
"use client"
//import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import dynamic from "next/dynamic";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Provider } from "react-redux";
import store, { persistor } from "./store/store"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const NoSSRTopBar = dynamic(() => import('./components/Topbar'), { ssr: false })
const NoSSRNavBar = dynamic(() => import('./components/Navbar'), { ssr: false })
const NoSSRFooter = dynamic(() => import('./components/Footer'), { ssr: false })
const NoSSRPersistorGate = dynamic(() => import('redux-persist/integration/react').then(mod => mod.PersistGate), { ssr: false })


/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //  const router = useRouter();
  // private route
  /*   const [isAuthorized , setIsAuthorized]= useState<boolean | null>(null)
    useEffect (()=>{
      const user = JSON.parse(localStorage.getItem("user") || "null");
      if(!user || !user.user){
        setIsAuthorized(false);
        router.push ('/login')
      }else if (user.user.item.includes("client")) {
        setIsAuthorized(true);
  
      }else{
              setIsAuthorized(false);
  
      }
    }) */

  //public route
  const [isAuthorized, setIsAuthorized] = useState<boolean | null>(false)
  const [isPersistGateReady, setIsPersistGateReady] = useState<boolean>(false)
  const router = useRouter();
  const pathname = usePathname()
  const islogin = pathname === "/login";
  const isRegister = pathname === "/register";
  const isForget = pathname === "/forget"
  const isAuth = pathname.startsWith("/reset");
  

  useEffect(() => {
    const user = localStorage.getItem("user") ;
    setIsPersistGateReady(true)

    if (!user) {
      setIsAuthorized(false);
    
      
    } else {
      setIsAuthorized(true);
      
      if (islogin || isRegister || isForget || isAuth) {
        router.push("/");
      }
    }
  }, [pathname, router]);
  if (isAuthorized === null) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gray-100">
        <div className="text-center">
          <div className="spinner border-t-4 border-blue-500 w-16 h-16 mx-auto rounded-full animate-spin"></div>
          <p className="text-lg font-semibold text-gray-700 mt-4">
            Loading your shopping experience...
          </p>
          <p className="text-sm text-gray-500">
            Please wait while we set up your account.
          </p>
        </div>
      </div>
    );
  }

  if (!isPersistGateReady){
    return <div>Loading ....</div> ;
  }

  return (
    <Provider store ={store}>
      <NoSSRPersistorGate loading={null} persistor={persistor}>

    <html lang="en">
      <head>
        <base href='/' />
        <link href="img/favicon.ico" rel="icon" />

        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />

        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
            <link
              href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
              rel="stylesheet"
            />
            <link
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css"
              rel="stylesheet"
            />


        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />


        <link href="css/style.css" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>


        <script src="mail/jqBootstrapValidation.min.js"></script>
        <script src="mail/contact.js"></script>

        <script src="js/main.js"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {
          islogin || isRegister || isForget || isAuth  ? (
            children
          ) : (<>
            <NoSSRTopBar />
            <NoSSRNavBar />
            {children}
            <NoSSRFooter />
            </>)
        }



      </body>
    </html>
      </NoSSRPersistorGate>

    </Provider>
  );
}
